language: node_js

node_js:
  - 12

notifications:
  email: false

branches:
  only:
    - main

script:
  - echo "test if gh-page deploy"
  - LATEST_COMMIT=$(git log -1 --format=format:%H --full-diff .)
  - LATEST_HTML_COMMIT=$(git log -1 --format=format:%H --full-diff ./html)
  - |
    if [[ $LATEST_COMMIT == $LATEST_HTML_COMMIT ]]
    then
      echo "Deploy Github Pages"
      HTML_FILES="index.html css imgs js"
      git remote add www https://thiagohersan:$GHTOKEN@github.com/astrolabe-www/algotypes-divination.git
      git checkout --orphan gh-pages
      git rm --cached -r . &> /dev/null
      pushd html
      cp -r $HTML_FILES ..
      popd
      git add $HTML_FILES
      git commit -m "update site" &> /dev/null
      git push www :gh-pages
      git push www gh-pages
    fi
